# Generated by Django 2.2.16 on 2021-08-25 06:46

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210825_0542'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_not_equals_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='user_not_equals_following'),
        ),
    ]
