# Generated by Django 2.2.16 on 2021-08-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210825_0646'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_not_equals_following',
        ),
    ]
